### ISSUE TITLE
Eliminate `tgver` branches of `tgvejs` and `app`

### ISSUE THREAD

**Issue by layik** [tgve/tgver#1]
To embed a TGVE app build in an R package two things needs to be taken care of:

1. Plotly cannot be a direct dependency.
2. Passing parameters to TGVE from R is done via some "string.keyword" pattern replacement.

For (1), without a branch, struggling to find another way, unless we take plotlyjs out of `tgvejs`/eAtlas.

For (2), currently the pattern replacement does the job, when data needs to be continuously replaced, every time clean copy is needed. There has to be a better build flow.

Consider this:
1. Top parent object reads from another file called settings.js
2. Only settings.js needs to be rewritten
3. R can generate the file on the fly based on the babel/webpack build.

Tasks:
- tgve/tgvejs#110
- [x] delete `npm-tgver` branch of `eAtlas`
- [x] delete `tgver` branch of `app`
- [x] update `tgver` functions (all of them) to stop `grep`ing (i.e remove `build` function)
- [x] document/find solution for minor change in `package.json` of `tgve/app` in order to build `tgve/app` as `tgve.zip` in this R package

**Comment by layik** [comment]
Updated this @rolyp. I think have mentioned this elsewhere, but obviously this is the right place/ticket.

**Comment by rolyp** [comment]
@layik Renamed and bumped to "in progress".

**Comment by layik** [comment]
Note to me: currently (25th Jan 2022), the bundled "build" has capacity to work with `tgver::build` function and also accept variables via URL. The latter taking priority means the R package should be functional whilst being overhauled.

**Comment by rolyp** [comment]
@layik Added a subtask to this to make a pass (you and I together) over the `README.md`.

**Comment by layik** [comment]
My note to self is slightly wrong. The package as of stamp of this comment is not functional. Will be sending a PR to keep it functional whilst being overhauled and can close #23

**Comment by layik** [comment]
@rolyp added subtask: document/find solution for minor change in package.json of tgve/app in order to build tgve/app as tgve.zip in this R package.

We cannot build `tgve/app` and use it in `tgver` as it is. There is minor change that is required which must be included in any automation script as well. Can document that somewhere else.

Solution: `tgve/app->package.json` includes a script tag that does this minor change. Will deal with it in the repo.

**Comment by layik** [comment]
@rolyp lets discuss 
> rename `master` to `release` for consistency with other repos?

I took it off the checkboxes just because this ticket title has been addressed now and both branches are deleted.

rOpenSci package reviews is a good "standard" for me and would have submitted `tgver` had it not been their condition to transfer the repo from this org to theirs once accepted.

However, they keep `master` or `main` even in their review repo: https://github.com/ropensci/software-review. So just in case, some `devtools`, `usethis` or other R dev packages refer to a default branch by name, I propose to leave it as either `master` or `main` and I know it falls outside the consistency in this organisation. Please let me know what your final decision is and I will go with it.

**Comment by rolyp** [comment]
@layik Let's retain `master` then (I've already purged the references to `main` from `.github/workflows`).

**Comment by layik** [comment]
Thanks @rolyp close the ticket when you are happy.
