### ISSUE TITLE
Automate deployment of `tgve/app` into `tgver`

### ISSUE THREAD

**Issue by rolyp** [tgve/tgver#20]
`tgve/app` is built and copied by hand (as a zip file containing a static website) into `tgver`. Automate this process, including testing via the R interface.
- [x] update R build automation to build/copy `tgve/app`
- [x] update `inst/tgve.R` to remove zip copy/delete

**Comment by layik** [comment]
Anything in `inst`, such as `inst/tgve.R`, is great to have towards 100% reproducibility. Actions scripts are not part of R packages so RE 2nd checkbox we want to replicate the automation for manual process somewhere in `inst/tgve.R`.

**Comment by layik** [comment]
@nbarlowATI and @LydiaFrance please notice the slight but critical change in building for tgver above and https://github.com/tgve/app/commit/967f79d5cd607243affffa1bb321981ca089cebf

**Comment by layik** [comment]
#31 via tgve/app#15 via tgve/tgvejs#116 :+1:

**Comment by nbarlowATI** [comment]
We think we are just about there now on the branch `20-automate-tgve.zip` - we have a Github action that should run at 1am every night, and:
* clone this repo and switch to the `20-automate-tgve.zip`
* Run the script `inst/tgve.R` which will:
  - Clone the `app` repo in a temporary dir
  - Switch to the `tgver_new_sed` branch
  - Run `yarn; yarn run tgver`
  - Create a zipfile from the contents of the build directory
  - Copy the zipfile to `inst/tgve.zip`

Once we merge the new sed command into the default branch of `app`, we can switch to using the default branches of both packages.   We will check tomorrow whether the `tgve.zip` file produced tonight looks good though...

**Comment by layik** [comment]
I just created https://github.com/tgve/app/pull/16

**Comment by layik** [comment]
Just an update from @nbarlowATI and me: we managed to get the separate action to run on R CMD ignoring vignettes locally but also prepared a merge of the action into tic. Nick will do the rest and we can PR final push from the branch.
