### ISSUE TITLE
R package documentation

### ISSUE THREAD

**Issue by rolyp** [tgve/tgver#26]
@layik Extracted from #1.

R packages often come with long-form documentation in the form of “vignettes” which describe common use-cases/scenarios. These are great but are another source of duplication/redundancy, so we will need to think about how best to manage that.

- [x] pass over `README.md`
- [x] evaluate relationship of each vignette to documentation stored elsewhere

**Comment by layik** [comment]
Post CRAN we can decide how we want to present the package as it will grow along with the npm package. I vote to close this until new docs is needed. cran requited doc work was done in #38
